[platformio]
src_dir = src-arduino
lib_dir = lib-arduino

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = qio
board_build.flash_size = 16MB

board_build.psram = enabled
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
    nrf24/RF24
    adafruit/Adafruit NeoPixel
    t-vk/ESP32 BLE Mouse
    adafruit/Adafruit PN532
